test: Fix indentation
This caused a warnings with GCC 6:

http.c: In function 'base64_encode_blockend':
http.c:138:2: error: statement is indented as if it were guarded by... [-Werror=misleading-indentation]
  return codechar - code_out;
  ^~~~~~
http.c:135:5: note: ...this 'if' clause, but it is not
     if (state_in->stepcount >= 0)
     ^~