Fix building without libcurl
If configured --without-libcurl, compilation failed with:

isds.c:11090:17: error: 'struct isds_ctx' has no member named 'curl'

This was caused by misplaced condition on libcurl support. This patch fixes it
together with similar mistake in offline tests.

Reported by Toralf Förster from Gentoo tinderbox testing
<https://bugs.gentoo.org/show_bug.cgi?id=571906>.